demand_index:
    path:     /
    defaults: { _controller: "TransBundle:Demand:index" }
    methods:  GET

demand_show:
    path:     /{id}/show
    defaults: { _controller: "TransBundle:Demand:show" }
    methods:  GET

demand_new:
    path:     /new
    defaults: { _controller: "TransBundle:Demand:new" }
    methods:  [GET, POST]

demand_edit:
    path:     /{id}/edit
    defaults: { _controller: "TransBundle:Demand:edit" }
    methods:  [GET, POST]

demand_delete:
    path:     /{id}/delete
    defaults: { _controller: "TransBundle:Demand:delete" }
    methods:  DELETE
