index:
    path:     /
    defaults: { _controller: TransBundle:Main:index }

demande:
    path:     /demande
    defaults: { _controller: TransBundle:Main:demande }

offerlist:
    path:     /{id}/offerlist
    defaults: { _controller: TransBundle:Main:offerlist }

com:
    path:     /com
    defaults: { _controller: TransBundle:Main:com }

rating:
    path:     /rating
    defaults: { _controller: TransBundle:Main:rating }

countdown:
    path:     /countdown
    defaults: { _controller: TransBundle:Main:countDown }