TransBundle\Entity\Demand:
    type: entity
    table: null
    repositoryClass: TransBundle\Repository\DemandRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        location:
            type: string
            length: 255
        languageNeeded:
            type: string
            length: 255
        languageSpoken:
            type: string
            length: 255
        institutionInvolved:
            type: string
            length: 255
        institutionName:
            type: string
            length: 255
        situation:
            type: text
        translator:
            type: integer
            nullable: true
        applicant:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }
