TransBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: TransBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255
        native_language:
            type: string
            length: 255
        paypal_account:
            type: string
            length: 255
        nationality:
            type: string
            length: 255
        translator:
            type: boolean
        profile_picture:
            type: string
            length: 255
        rating:
            type: integer
            nullable: true
        rate_number:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }