# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
# Override fosuser form template
    app.form.registration:
        class: TransBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
  # [...] Vos autres services
    redirect.after.login:
        class: UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]

    redirect.after.logout:
        class: UserBundle\Redirection\AfterLogoutRedirection
        arguments: [@router, @security.context]

# Repository to stock queries to get translators' lists.
    main.repository:
        class: TransBundle\Repository\MainRepository