<?php

namespace TransBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandRepository extends EntityRepository
{
}
